services:
  db:
    image: postgres:18
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shiftly
    volumes:
      - shiftly-pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost -p 5432 -d shiftly"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  shiftly-pgdata:
