packages:
  - "apps/*"
  - "packages/*"

catalog:
  effect: ^3.22.2
  "@effect/platform": ^0.97.2
  "@effect/platform-node": ^0.108.2

minimumReleaseAge: 4320

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  esbuild: true
  msgpackr-extract: true
  msw: false
